AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Slack Analytics Bot - SAM Template (TypeScript / Node.js)

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 120
    MemorySize: 1024
    Tracing: Active
    Environment:
      Variables:
        LOG_LEVEL: !Ref LogLevel
        SLACK_BOT_TOKEN: !Ref SlackBotToken
        SLACK_SIGNING_SECRET: !Ref SlackSigningSecret
        OPENAI_API_KEY: !Ref OpenAIKey
        OPENAI_MODEL: !Ref OpenAIModel
        REPORT_CHANNEL_ID: !Ref ReportChannelId
        OPENAI_QA_SYSTEM_PROMPT: !Ref OpenAIQASystemPrompt
        OPENAI_REPORT_SYSTEM_PROMPT: !Ref OpenAIReportSystemPrompt
        DB_HOST: !Ref DbHost
        DB_PORT: !Ref DbPort
        DB_USER: !Ref DbUser
        DB_PASSWORD: !Ref DbPassword
        DB_NAME: !Ref DbName

Parameters:
  SlackBotToken:
    Type: String
    NoEcho: true
    Description: Slack Bot User OAuth Token (starts with xoxb-)
  SlackSigningSecret:
    Type: String
    NoEcho: true
    Description: Slack App Signing Secret
  ReportChannelId:
    Type: String
    Default: ""
    Description: Slack channel ID to post scheduled reports
  DbHost:
    Type: String
    Default: ""
    Description: MySQL hostname
  DbPort:
    Type: String
    Default: "3306"
    Description: MySQL port
  DbUser:
    Type: String
    Default: ""
    Description: MySQL username
  DbPassword:
    Type: String
    Default: ""
    NoEcho: true
    Description: MySQL password
  DbName:
    Type: String
    Default: ""
    Description: MySQL database name
  OpenAIKey:
    Type: String
    NoEcho: true
    Description: OpenAI API Key
  OpenAIModel:
    Type: String
    Default: gpt-5-nano
    Description: OpenAI Chat Model (e.g. gpt-5-nano)
  OpenAIQASystemPrompt:
    Type: String
    Default: |
      ë‹¹ì‹ ì€ MySQL ì „ë¬¸ê°€ìž…ë‹ˆë‹¤.\nì‚¬ìš©ìžê°€ ìžì—°ì–´ë¡œ ìš”ì²­í•˜ë©´, ì•ˆì „í•˜ê³  ìœ íš¨í•œ MySQL SQLë¬¸ë§Œ ìž‘ì„±í•˜ì‹­ì‹œì˜¤. \në³µìž¡í•œ ì§‘ê³„, ê·¸ë£¹í•‘, ì„œë¸Œì¿¼ë¦¬, CTE, ìœˆë„ìš° í•¨ìˆ˜ ì‚¬ìš©ë„ í—ˆìš©ë©ë‹ˆë‹¤.\n\n[DB ìŠ¤í‚¤ë§ˆ]\n- user_action(user_action_idx, user_action_type, ceo_idx, extra_data, ins_date)\n- ceo(ceo_idx, corp_idx)\n- tbl_corp(corp_idx, corp_name)\n\n[ê·œì¹™]\n1. user_action.ceo_idx â†’ corp_nameìœ¼ë¡œ ë³€í™˜í•˜ì—¬ ì¶œë ¥ (tc.corp_name ì»¬ëŸ¼ í¬í•¨)\n2. ë¶ˆí•„ìš”í•œ ì»¬ëŸ¼ ì œì™¸\n3. ê°€ëŠ¥í•˜ë‹¤ë©´ ë§ˆíŠ¸ë³„ë¡œ í†µí•©, ë¶ˆê°€ëŠ¥í•˜ë‹¤ë©´ ë§ˆíŠ¸ ì´ë¦„ìˆœìœ¼ë¡œ ì •ë ¬\n4. SELECT êµ¬ë¬¸ë§Œ ìž‘ì„±, MySQLì—ì„œ ì‹¤í–‰ ê°€ëŠ¥í•´ì•¼ í•¨\n5. ìœˆë„ìš° í•¨ìˆ˜(AVG, STDDEV ë“±), CTE, ì„œë¸Œì¿¼ë¦¬ ì‚¬ìš© ê°€ëŠ¥\n6. ë‹µë³€ì€ SQLë¬¸ë§Œ ë°˜í™˜ (ì„¤ëª…, ì£¼ì„, ì½”ë“œ ë¸”ë¡ ê¸ˆì§€)\n7. ì†Œìˆ˜ì  ì´í•˜ í•œ ìžë¦¬ê¹Œì§€ë§Œ í‘œì‹œ\n\n[ì´ë²¤íŠ¸ ê·¸ë£¹]\n- í•µì‹¬: print_pop, save_pamphlet, send_message (ë¹„êµ/ë¹„ìœ¨ ë¶„ì„ìš©)\n- ì°¸ê³ : visit, save_pop (í•„ìš” ì‹œ ë‹¨ìˆœ ì¹´ìš´íŠ¸)\n\n[ì¶œë ¥ ì˜ˆì‹œ]\nSELECT tc.corp_name AS mart_name,\n       COUNT(*) AS save_pamphlet_count\nFROM user_action ua\nJOIN ceo c ON ua.ceo_idx = c.ceo_idx\nJOIN tbl_corp tc ON c.corp_idx = tc.corp_idx\nWHERE ua.user_action_type = 'save_pamphlet'\nGROUP BY tc.corp_name\nORDER BY tc.corp_name;
    Description: System prompt used for mention Q&A
  OpenAIReportSystemPrompt:
    Type: String
    Default: |
      ë‹¹ì‹ ì€ ì „ë¬¸ ë°ì´í„° ë¶„ì„ê°€ìž…ë‹ˆë‹¤.  \nì£¼ì–´ì§„ JSON ì‚¬ìš©ìž ë¡œê·¸ ë°ì´í„°ë¥¼ ê¸°ë°˜ìœ¼ë¡œ, ì‚¬ì‹¤ì— ê·¼ê±°í•œ ì²´ê³„ì ì´ê³  ê°€ë…ì„±ì´ ë†’ì€ ë°ì´í„° ë¶„ì„ ë³´ê³ ì„œë¥¼ ìž‘ì„±í•˜ì‹­ì‹œì˜¤.\n\n[ë¶„ì„ ëª©ì ]\n- í™œì„±Â·ìœ ìž…Â·ì´íƒˆ ì‚¬ìš©ìž ë“± ì½”í˜¸íŠ¸ ë¶„ì„\n- ë§ˆíŠ¸(ì‚¬ìš©ìž) í–‰ë™ íŒ¨í„´ê³¼ íŠ¸ë Œë“œ ë¶„ì„\n- ê¸°ê°„ë³„(ì£¼Â·ì›”Â·ìš”ì¼) ë¹„êµë¥¼ í†µí•œ íŒ¨í„´, íŠ¸ë Œë“œ, ì´ìƒì¹˜ ë¶„ì„ ë° ì‹œì‚¬ì  í™•ì¸\n\n[ê·œì¹™]\n- ë³´ê³ ì„œì—ëŠ” ì›ì²œ JSON ë°ì´í„°ëŠ” í¬í•¨í•˜ì§€ ë§ê³ , ì˜¤ì§ ìš”ì•½ê³¼ ì¸ì‚¬ì´íŠ¸ ì¤‘ì‹¬ìœ¼ë¡œ ìž‘ì„±\n- ê°€ë…ì„±ì„ ìµœìš°ì„ ìœ¼ë¡œ í•  ê²ƒ\n- ëª¨ë“  ìˆ˜ì¹˜ëŠ” ë°˜ë“œì‹œ ì–´ë–¤ ì´ë²¤íŠ¸ ë˜ëŠ” ì§€í‘œë¥¼ ë‚˜íƒ€ë‚´ëŠ”ì§€ ëª…ì‹œì ìœ¼ë¡œ í‘œì‹œ\n- ë³´ê³ ì„œ ë‚´ìš©ê³¼ ê´€ë ¨ ì—†ëŠ” ì¶”ê°€ ì œì•ˆì€ ê¸ˆì§€ (ì˜ˆ: ì¶”ê°€ ë¶„ì„, ì‹œê°í™”, ì½”ë“œ)\n- ì›”ê°„/ì£¼ê°„/ìš”ì¼ë³„ ë¹„êµ ë° ì¦ê°ë¥ , ì£¼ìš” íŒ¨í„´, ì´ìƒì¹˜, í•µì‹¬ ì‹œì‚¬ì  ë“±ì„ ê°•ì¡°\n\n[ì¶œë ¥ í˜•ì‹]\n- Slack ë©”ì‹œì§€ìš© blocks í˜•ì‹ìœ¼ë¡œ ìž‘ì„±, ìµœì¢… ê²°ê³¼ë¬¼ì€ í•­ìƒ JSON ë°°ì—´ '[ ... ]' í˜•ì‹ì´ì–´ì•¼ í•¨\n- ì§€í‘œ ìš”ì•½ì€ ë°˜ë“œì‹œ ì½”ë“œë¸”ëŸ­ '``` ```' ì•ˆì— ìž‘ì„±í•  ê²ƒ\n- í…ìŠ¤íŠ¸ëŠ” mrkdwn í˜•ì‹ìœ¼ë¡œ ìž‘ì„±í•˜ì—¬ ê°•ì¡°, ê¸€ë¨¸ë¦¬í‘œ, ë²ˆí˜¸ ë“±ì„ ìžìœ ë¡­ê²Œ í™œìš©\n- ë“¤ì—¬ì“°ê¸°ëŠ” ë„ì–´ì“°ê¸° ë„¤ ì¹¸ ì‚¬ìš©\n- 'ì½”í”„/ì½”í¼ë ˆì´ì…˜/ê¸°ì—…/ìƒì ' ë“±ì€ ëª¨ë‘ 'ë§ˆíŠ¸'ë¡œ í†µì¼\n- ê° ë¸”ë¡ì—ëŠ” section, header, context ë“± Slackì—ì„œ ì§€ì›í•˜ëŠ” ë¸”ë¡ íƒ€ìž…ì„ í™œìš©\n\n[ì˜ˆì‹œ êµ¬ì¡°]\n[\n  {\n    \"type\": \"header\",\n    \"text\": {\n      \"type\": \"plain_text\",\n      \"text\": \"ðŸ“‹ 9ì›” 7ì¼ ë°ì´í„° ë¶„ì„ ë³´ê³ ì„œ\"\n    }\n  },\n  {\n    \"type\": \"section\",\n    \"text\": {\n      \"type\": \"mrkdwn\",\n      \"text\": \"*1. í•µì‹¬ ìš”ì•½*\\n ...\"\n    }\n  },\n  ...\n]
    Description: System prompt used for report generation
  LogLevel:
    Type: String
    Default: INFO
    AllowedValues: [CRITICAL, ERROR, WARNING, INFO, DEBUG]
    Description: Log level for functions
  ScheduleExpression:
    Type: String
    Default: cron(0 23 ? * SUN *)
    Description: >-
      EventBridge schedule for weekly report. Default is 23:00 UTC Sunday
      (08:00 Monday KST).

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      TracingEnabled: true

  MentionQnAFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: handlers/answerMention.handleSlackMentionQnA
      Events:
        SlackEvents:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /slack/events
            Method: POST
      ReservedConcurrentExecutions: 1
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "node20"
        Sourcemap: true
        EntryPoints:
          - src/handlers/answerMention.ts
        External:
          - aws-sdk

  GenerateReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: handlers/generateReport.generateAnalyticsReport
      Events:
        WeeklySchedule:
          Type: Schedule
          Properties:
            Schedule: !Ref ScheduleExpression
      ReservedConcurrentExecutions: 1
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "node20"
        Sourcemap: true
        EntryPoints:
          - src/handlers/generateReport.ts
        External:
          - aws-sdk

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL for Slack events
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/slack/events
